runtime: python310
instance_class: F2

entrypoint: gunicorn -w 4 -k gthread --log-level debug pizzaria.pizzaria.wsgi:application

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: 'pizzaria.pizzaria.settings'
